# Generated by Django 2.0.2 on 2018-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='summary',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
